/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2018-02-08 10:35:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1517835649000L));
    _jspx_dependants.put("jar:file:/home/spaneos/workspace/project1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/com.spaneos.shoppingcart/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("\n");
      out.write("<title>Shopping</title>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"home.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"shopping.css\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("div.transbox {\n");
      out.write("\tmargin: 100px;\n");
      out.write("\tborder: 0px solid black;\n");
      out.write("\tborder-radius: 10px;\n");
      out.write("\tpadding: 50px 30px 50px 80px;\n");
      out.write("\topacity: 0.8;\n");
      out.write("\tfilter: alpha(opacity = 60); /* For IE8 and earlier */\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body background=\"shopping_home.jpg\">\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write(" \n");
      out.write("\t\t<div class=\"row\" style=\"background-color: #3e3436\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md-1\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"menu-wrap\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<nav class=\"menu\">\n");
      out.write("\t\t\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t\t\t<a href=\"admin_page.jsp\">&nbsp&nbsp&nbsp Admin Home <span\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\"></span>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Categories</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Users</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md-1  col-md-offset-10\">\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"glyphicon glyphicon-log-out\"></span>\n");
      out.write("\t\t\t\t\t\t\tLogout</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write(" \n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md-6  col-md-offset-3\">\n");
      out.write("\n");
      out.write("\t\t\t\t<form action=\"addProducts.jsp\" method=\"post\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<button style=\"text-align: right;\" href=\"admin_page.jsp\">back</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-footer\" style=\"text-align:center;\"\t>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" data-toggle=\"modal\" data-target=\"#Products\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\tadd products</b>\n");
      out.write("\t\t\t\t\t\t\t\t\t</button></div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Modal -->\n");
      out.write("\n");
      out.write("\t<div class=\"modal fade\" id=\"Products\" role=\"dialog\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- Modal content-->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">Add Product</h4>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<form  method=\"post\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"pname\" id=\"pname\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Product Name \" required><br>\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"5\" name=\"pdes\" id=\"pdes\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Product Description\" required></textarea>\n");
      out.write("\t\t\t\t\t\t<br> <input type=\"number\" class=\"form-control\" name=\"pno\"\n");
      out.write("\t\t\t\t\t\t\tid=\"pno\" placeholder=\"enter available count \" required><br>\n");
      out.write("\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" name=\"price\" id=\"price\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"enter price of product \" required><br>\n");
      out.write("\t\t\t\t\t\t<select name=\"pcat\" id=\"pcat\">\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</select></br> </br>\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\" id=\"login\">Add\n");
      out.write("\t\t\t\t\t\t\tProducts</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<button type=\"reset\" class=\"btn btn-danger\" data-dismiss=\"modal\">Clear</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<form action=\"editProducts.jsp\" method=\"post\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"modal fade\" id=\"editProducts\" role=\"dialog\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Modal content-->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">editProduct</h4>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"pname\" id=\"pname\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Product Name \" value=\"\" required><br>\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"5\" name=\"pdes\" id=\"pdes\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Product Description\" required value=\"\"></textarea>\n");
      out.write("\t\t\t\t\t\t\t<br> <input type=\"number\" class=\"form-control\" name=\"pno\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"pno\" placeholder=\"enter available count \" required value=\"\"><br>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" name=\"price\" id=\"price\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"enter price of product \" required value=\" \"><br>\n");
      out.write("\t\t\t\t\t\t\t<select name=\"pcat\" id=\"pcat\">\n");
      out.write("\t\t\t\t\t\t\t\t<a data-toggle=\"modal\" data-target=\"#Category\" name=\"ctg\"\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t</select></br> </br>\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\" id=\"login\">Add\n");
      out.write("\t\t\t\t\t\t\t\tProducts</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Clear</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"transbox\">\n");
      out.write("\n");
      out.write("\t\t\t<table width=\"100%\" border=\"1\">\n");
      out.write("\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<th width=\"30%\">Product Name</th>\n");
      out.write("\t\t\t\t\t<th width=\"40%\">Product Description</th>\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Products Available</th>\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Price</th>\n");
      out.write("\t\t\t\t\t<th width=\"10%\">edit</th>\n");
      out.write("\t\t\t\t\t<th width=\"10%\">Delete</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div class=\"footer\">\n");
      out.write("\t\t<div row=\"\" style=\"background-color: #3e3436;\">\n");
      out.write("\t\t\t<div class=\"col-md-4\" style=\"background-color: #3e3436;\">\n");
      out.write("\t\t\t\t<h4 style=\"color: silver;\" align=\"center\">copyright@spaneos.com</h4>\n");
      out.write("\t\t\t\t<h4 style=\"color: silver;\" align=\"center\">Spaneos Software\n");
      out.write("\t\t\t\t\tSolution Pvt.Ltd</h4>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-md-4\" style=\"background-color: #3e3436;\">\n");
      out.write("\t\t\t\t<h4 style=\"color: silver;\" align=\"center\">ph:741120485</h4>\n");
      out.write("\t\t\t\t<h4 style=\"color: silver;\" align=\"center\">email:\n");
      out.write("\t\t\t\t\tpush.123@spaneos.com</h4>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-md-4\" style=\"background-color: #3e3436;\">\n");
      out.write("\t\t\t<h4 style=\"color: silver;\"></h4>\n");
      out.write("\t\t\t<h4 style=\"color: silver;\"></h4>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /addProduct.jsp(95,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/addProduct.jsp(95,7) '${catList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${catList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /addProduct.jsp(95,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("cList");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"modal-title\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\tcategory : <u><b>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cList.cat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b></u>\n");
          out.write("\t\t\t\t\t\t\t\t\t</h2>\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"modal-body\">\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<p>Description :</p>\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<textarea rows=\"4\" cols=\"50\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cList.des}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</textarea>\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /addProduct.jsp(159,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/addProduct.jsp(159,7) '${catList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${catList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /addProduct.jsp(159,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("cList");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t<option><a data-toggle=\"modal\" data-target=\"#Category\"\n");
          out.write("\t\t\t\t\t\t\t\t\t\tname=\"ctg\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cList.cat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cList.cat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></option>\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /addProduct.jsp(243,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/addProduct.jsp(243,4) '${productList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /addProduct.jsp(243,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("pList");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<tr>\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pList.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pList.pdes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pList.pno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pList.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("\t\t\t\t\t\t<td><a href=\"editProduct.Ado?prodval=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pList.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><span\n");
          out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-pencil\"></span></td>\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t<td><a href=\"deleteProduct.Ado?catval=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pList.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><span\n");
          out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-trash\"></span></td>\n");
          out.write("\t\t\t\t\t</tr>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }
}
