/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2018-02-09 07:19:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spaneos.online_shopping.CategoryBean;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1517835649000L));
    _jspx_dependants.put("jar:file:/home/spaneos/workspace/project1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/com.spaneos.shoppingcart/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.spaneos.online_shopping.CategoryBean");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("    <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("    <html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <link rel=\"stylesheet\"\n");
      out.write("            href=\"http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css\" />\n");
      out.write("   \n");
      out.write("   <link rel=\"stylesheet\"\n");
      out.write("           href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("   <link rel=\"stylesheet\"\n");
      out.write("           href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("   \n");
      out.write("   <script\n");
      out.write("           src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("   <script\n");
      out.write("           src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("   <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\n");
      out.write("   <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("   <script\n");
      out.write("           src=\"https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js\"></script>\n");
      out.write("   <head>\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("   <title>Cart</title>\n");
      out.write("   <link rel=\"stylesheet\" href=\"\">\n");
      out.write("   <link rel=\"stylesheet\" href=\"shopping.css\">\n");
      out.write("   <script type=\"text/javascript\">\n");
      out.write("           function disableF5(e) {\n");
      out.write("                   if ((e.which || e.keyCode) == 116 || (e.which || e.keyCode) == 82)\n");
      out.write("                           e.preventDefault();\n");
      out.write("           };\n");
      out.write("   \n");
      out.write("           $(document).ready(function() {\n");
      out.write("                   $(document).on(\"keydown\", disableF5);\n");
      out.write("           });\n");
      out.write("   </script>\n");
      out.write("   </head>\n");
      out.write("   <body background=\"shopping_home.jpg\">\n");
      out.write("           <!--Navigation bar -->\n");
      out.write("           <nav class=\"navbar navbar-inverse\" style=\"background-color: #808080;\">\n");
      out.write("           <div class=\"container-fluid\">\n");
      out.write("   \n");
      out.write("                   <div class=\"row\" style=\"background-color: #808080;\">\n");
      out.write("                           <div class=\"col-md-4\">\n");
      out.write("                                   <h1 style=\"color: white; font-family: fantasy; font-weight: 800;\">\n");
      out.write("                                           <b>Shopping  shop hear</b>\n");
      out.write("                                   </h1>\n");
      out.write("                           </div>\n");
      out.write("                           <div class=\"col-md-1 col-md-offset-5\">\n");
      out.write("                                   <h5>\n");
      out.write("                                           <a href=\"goUser.Udo\" style=\"color: white;\">home</a>\n");
      out.write("                                   </h5>\n");
      out.write("                           </div>\n");
      out.write("                           <div class=\"col-md-1 \">\n");
      out.write("                                   <h5 style=\"color: black;\">\n");
      out.write("                                           <a href=\"goUser.Udo\" style=\"color: white;\">Welcome : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("                                   </h5>\n");
      out.write("                           </div>\n");
      out.write("   \n");
      out.write("                           <div class=\"col-md-1\">\n");
      out.write("                                   <h5>\n");
      out.write("                                           <a href=\"logout.Udo\" style=\"color: black;\">Logout</a>\n");
      out.write("                                   </h5>\n");
      out.write("                           </div>\n");
      out.write("   \n");
      out.write("                   </div>\n");
      out.write("           </nav>\n");
      out.write("           <b style=\"color: red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>\n");
      out.write("           <b style=\"color: red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>\n");
      out.write("           <!-- Displaying Cart Details -->\n");
      out.write("           <div id=\"container\" style=\"margin-left: 10%; margin-right: 10%;\">\n");
      out.write("                   <h3 align=\"center\">\n");
      out.write("                           <u><b>Cart Details</b></u>\n");
      out.write("                   </h3>\n");
      out.write("                   <form action=\"viewcart.Udo\" method=\"post\">\n");
      out.write("                           <table class=\"table table-bordered\" bgcolor=\"#00FF00\">\n");
      out.write("                                   <thead>\n");
      out.write("                                           <tr>\n");
      out.write("                                                   <th></th>\n");
      out.write("                                                   <th>Products</th>\n");
      out.write("                                                   <th>Price</th>\n");
      out.write("                                                   <th>No. Of Units</th>\n");
      out.write("                                                   <th></th>\n");
      out.write("   \n");
      out.write("                                           </tr>\n");
      out.write("                                   </thead>\n");
      out.write("                                   <tbody>\n");
      out.write("                                           ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  \n");
      out.write("                                  </tbody>\n");
      out.write("                          </table>\n");
      out.write("                          <!-- Button to CheckOut-->\n");
      out.write(" \n");
      out.write("                          <button type=\"button\" class=\"btn btn-primary\" style=\"float: right;\"\n");
      out.write("                                  data-toggle=\"modal\" data-target=\"#myModal\">Chek Out</button>\n");
      out.write("                  </form>\n");
      out.write("                \n");
      out.write("                  <!-- Button to go to main page-->\n");
      out.write("                  <a href=\"goUser.Udo\"><button type=\"submit\" id=\"opener\"\n");
      out.write("                                  class=\"btn btn-primary\" style=\"float: left;\">Browse More\n");
      out.write("                                 Items</button></a>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          \n");
      out.write("          <!-- Modal -->\n");
      out.write("          \n");
      out.write("                 <div id=\"myModal\" class=\"modal fade\" role=\"dialog\">\n");
      out.write("                          <div class=\"modal-dialog\">\n");
      out.write("  \n");
      out.write("  \n");
      out.write("                                  <form action=\"checkout.Udo\">\n");
      out.write("                                         <!-- Modal content-->\n");
      out.write("                                          <div class=\"modal-content\">\n");
      out.write("                                                  <div class=\"modal-header\">\n");
      out.write("                                                          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                                                          <h4 class=\"modal-title\" align=\"center\">Total Amount to Pay</h4>\n");
      out.write("                                                  </div>\n");
      out.write("                                                  <div class=\"modal-body\">\n");
      out.write("                                                          <p align=\"center\" style=\"color: red;\">\n");
      out.write("                                                                  <b>&#x20b9; </b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalamount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("                                                  </div>\n");
      out.write("                                                  <div class=\"modal-footer\">\n");
      out.write("                                                          <input type=\"submit\" class=\"btn btn-success\" value=\"Pay\" />\n");
      out.write("                                                          <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                                                  </div>\n");
      out.write("                                         </div>\n");
      out.write("  \n");
      out.write("                                  </form>\n");
      out.write("  \n");
      out.write("                          </div>\n");
      out.write("                  </div>\n");
      out.write("          \n");
      out.write("  \n");
      out.write(" </body>\n");
      out.write("  </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /cart.jsp(90,43) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/cart.jsp(90,43) '${cartList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cartList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /cart.jsp(90,43) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("name");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                                   <tr>\n");
          out.write("                                                           <td><input type=\"checkbox\" name=\"names\"\n");
          out.write("                                                                   value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" /></td>\n");
          out.write("                                                           <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                                                           <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                                                           <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.items}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                                                           <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                                                           <td><a href=\"DelCartItem.Udo?names=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" \"> <span\n");
          out.write("                                                                           class=\"glyphicon glyphicon-trash\"></span></a></td>\n");
          out.write("   \n");
          out.write("  \n");
          out.write("                                                  </tr>\n");
          out.write("                                          ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
