/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2018-02-09 07:08:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>User home</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"home.css\">\n");
      out.write("</head>\n");
      out.write("<body background=\"shopping_home.jpg\">\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\">Shopping center</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t<li><a href=\"#mySignUp\" data-toggle=\"modal\"\n");
      out.write("\t\t\t\tdata-target=\"#mySignUp\"><span class=\"glyphicon glyphicon-user\"></span>\n");
      out.write("\t\t\t\t\tSign Up</a></li>\n");
      out.write("\t\t\t<li><a href=\"#myLogin\" data-toggle=\"modal\"\n");
      out.write("\t\t\t\tdata-target=\"#myLogin\"><span class=\"glyphicon glyphicon-log-in\"></span>\n");
      out.write("\t\t\t\t\tLogin</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<form action=\"userhomeInter.jsp\" method=\"post\">\n");
      out.write("\t\t<!-- Modal for user login-->\n");
      out.write("\t\t<div class=\"modal fade\" id=\"myLogin\" role=\"dialog\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t<!-- Modal content-->\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">User Login</h4>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t<table  >\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"50\" width=\"30%\"><label>UserId:</label></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"50\" width=\"70%\"><input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"uid\" id=\"uid\" required></td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"50\" width=\"30%\"><label>Password:</label></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"50\" width=\"70%\"><input type=\"text\" type=\"password\" \n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"psw\" id=\"psw\" required></td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\" id=\"login\">Login</button>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<center>\n");
      out.write("\t\t\t\t\t\t<p style=\"color: red;\">");
      out.write(" </p>\n");
      out.write("\t\t\t\t\t</center>\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t<p>*All fields are mandatory</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Modal for sign-up-->\n");
      out.write("\t\t<div class=\"modal fade\" id=\"mySignUp\" role=\"dialog\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t<!-- Modal content-->\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">New User Registration</h4>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t        <form action=\"registerInter.jsp\" method=\"get\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t\tUser Name:<input type=\"text\" class=\"form-control\" name=\"name\" id=\"name\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Enter your name\" required><br> \n");
      out.write("\t\t\t\t\t\t\tEmail:<input type=\"text\" class=\"form-control\" type=\"email\" name=\"email\" id=\"email\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Enter your email id\" required><br>\n");
      out.write("\t\t\t\t\t\t\tPassword:<input type=\"text\" class=\"form-control\" type=\"password\"  name=\"pass\" id=\"pass\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Enter password\" required><br>\n");
      out.write("\t\t\t\t\t\t\tConfirm-Pwd:<input type=\"text\" class=\"form-control\" type=\"password\"  name=\"rpass\" id=\"rpass\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Confirm password\" required><br>\n");
      out.write("\t\t\t\t\t\t\tMob number:<input type=\"text\" class=\"form-control\" name=\"mobile\" id=\"mobile\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Enter your mobile no.\" required><br>\n");
      out.write("\t\t\t\t\t\t\tDob:<input type=\"date\" class=\"form-control\" name=\"date\" id=\"date\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"mm/dd/yyyy\" required><br> <input\n");
      out.write("\t\t\t\t\t\t\ttype=\"radio\" name=\"optradio\"  value=\"male\" checked></br>\n");
      out.write("\t\t\t\t\t\t\tMale: <input type=\"radio\"name=\"optradio\"  value=\"female\">Female: <br>\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"form-control\"name=\"address\" rows=\"5\" id=\"comment\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Billing Address\" required></textarea>\n");
      out.write("\t\t\t\t\t\t\t<br> <input type=\"checkbox\" value=\"\" required> I agree to all\n");
      out.write("\t\t\t\t\t\t\tthe terms and conditions.<br> <br>\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\" id=\"reg\">Register</button>\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Clear</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<center>\n");
      out.write("\t\t\t\t\t\t<p style=\"color: red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\t\t\t\t\t</center>\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t<p>*All fields are mandatory</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
